### ISSUE TITLE
"cli.js-fetch(1) does not exist" error

### ISSUE THREAD

**Issue by japj** [creationix/jsgit#5]
After installing jsgit freshly on a Windows 8.1 64bit system (using node v0.10.20) I try to follow the example it fails with a command error.

<pre>
C:\Projects\jsgit>npm install -g jsgit
..
npm http GET https://registry.npmjs.org/jsgit/-/jsgit-0.3.2.tgz
..
C:\Users\japj\AppData\Roaming\npm\jsgit-fetch -> C:\Users\japj\AppData\Roaming\npm\node_modules\jsgit\bin\fetch.js
C:\Users\japj\AppData\Roaming\npm\jsgit-log -> C:\Users\japj\AppData\Roaming\npm\node_modules\jsgit\bin\log.js
C:\Users\japj\AppData\Roaming\npm\jsgit-export -> C:\Users\japj\AppData\Roaming\npm\node_modules\jsgit\bin\export.js
C:\Users\japj\AppData\Roaming\npm\jsgit-ls-remote -> C:\Users\japj\AppData\Roaming\npm\node_modules\jsgit\bin\ls-remote.js
C:\Users\japj\AppData\Roaming\npm\jsgit -> C:\Users\japj\AppData\Roaming\npm\node_modules\jsgit\bin\cli.js
jsgit@0.3.2 C:\Users\japj\AppData\Roaming\npm\node_modules\jsgit
├── commander@2.0.0
└── git-node@0.1.1 (git-fs-db@0.2.0, git-net@0.0.4, js-git@0.5.2, git-node-platform@0.1.4)

C:\Projects\jsgit>jsgit fetch git://github.com/creationix/conquest.git

  cli.js-fetch(1) does not exist, try --help
</pre>

**Comment by japj** [comment]
note that `jsgit-fetch git://github.com/creationix/conquest.git` does seem to work, so it is something related to resolving commands from the 'main' application

**Comment by creationix** [comment]
Sounds like a bug in commander (the li easy I use for CLI parsing).  I'm glad it works at all though.

**Comment by whyleee** [comment]
Same issue for me, Windows 7 64bit, node v0.10.21. Not only `fetch` is not working, other commands also.
